[project]
name = "SqueakPoseStudio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyqt6>=6.10.0",
    "torch>=2.9.1",
    "ultralytics>=8.3.233",
]
